# Generated by Django 5.2.1 on 2025-05-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report_generator", "0002_studentreport_delete_report_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(db_index=True, max_length=64)),
                (
                    "report_type",
                    models.CharField(
                        choices=[("html", "HTML"), ("pdf", "PDF")], max_length=10
                    ),
                ),
                ("html_content", models.TextField(blank=True, null=True)),
                ("pdf_file", models.BinaryField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="StudentReport",
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["student_id", "report_type"],
                name="report_gene_student_ad5fff_idx",
            ),
        ),
    ]
