# Generated by Django 5.2.1 on 2025-05-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report_generator", "0003_report_delete_studentreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="namespace",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["namespace", "student_id", "report_type"],
                name="report_gene_namespa_beb601_idx",
            ),
        ),
    ]
