# Generated by Django 5.2.1 on 2025-05-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report_generator", "0005_studentreport_delete_report_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="studentreport",
            name="report_gene_student_b92024_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentreport",
            name="report_gene_task_id_969baf_idx",
        ),
        migrations.AlterUniqueTogether(
            name="studentreport",
            unique_together={("student_id", "namespace")},
        ),
        migrations.AddField(
            model_name="studentreport",
            name="html_task_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentreport",
            name="pdf_task_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="namespace",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="studentreport",
            index=models.Index(
                fields=["student_id"], name="report_gene_student_9fa2d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentreport",
            index=models.Index(
                fields=["namespace"], name="report_gene_namespa_fd1556_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="studentreport",
            name="report_type",
        ),
        migrations.RemoveField(
            model_name="studentreport",
            name="task_id",
        ),
    ]
